# Generated by Django 5.1.7 on 2025-03-16 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='time',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
