# Generated by Django 5.1.6 on 2025-04-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cleaner_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_rating',
            field=models.IntegerField(null=True),
        ),
    ]
