# Generated by Django 5.1.6 on 2025-03-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('CLEANER', 'Cleaner')], help_text='Required. Select an account type.', max_length=50),
        ),
    ]
