# Generated by Django 5.1.6 on 2025-03-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0003_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.IntegerField(max_length=1, null=True),
        ),
    ]
