# Generated by Django 5.1.6 on 2025-04-07 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0007_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Address must be in the format: State, Suburb, AddressNumber Street', regex='^[A-Za-z\\s]+,\\s*[A-Za-z\\s]+,\\s*\\d+\\s+[A-Za-z\\s]+$')]),
        ),
    ]
